
declare module HTML {

    type Tags = (
        'a' |
        'abbr' |
        'acronym' |
        'address' |
        'applet' |
        'area' |
        'article' |
        'aside' |
        'audio' |
        'b' |
        'base' |
        'basefont' |
        'bdo' |
        'big' |
        'blockquote' |
        'body' |
        'br' |
        'button' |
        'canvas' |
        'caption' |
        'center' |
        'cite' |
        'code' |
        'col' |
        'colgroup' |
        'data' |
        'datalist' |
        'dd' |
        'del' |
        'dfn' |
        'dir' |
        'div' |
        'dl' |
        'dt' |
        'em' |
        'embed' |
        'fieldset' |
        'figcaption' |
        'figure' |
        'font' |
        'footer' |
        'form' |
        'frame' |
        'frameset' |
        'h1' |
        'h2' |
        'h3' |
        'h4' |
        'h5' |
        'h6' |
        'head' |
        'header' |
        'hgroup' |
        'hr' |
        'html' |
        'i' |
        'iframe' |
        'img' |
        'input' |
        'ins' |
        'isindex' |
        'kbd' |
        'keygen' |
        'label' |
        'legend' |
        'li' |
        'link' |
        'listing' |
        'map' |
        'mark' |
        'marquee' |
        'menu' |
        'meta' |
        'meter' |
        'nav' |
        'nextid' |
        'nobr' |
        'noframes' |
        'noscript' |
        'object' |
        'ol' |
        'optgroup' |
        'option' |
        'output' |
        'p' |
        'param' |
        'picture' |
        'plaintext' |
        'pre' |
        'progress' |
        'q' |
        'rt' |
        'ruby' |
        's' |
        'samp' |
        'script' |
        'section' |
        'select' |
        'slot' |
        'small' |
        'source' |
        'span' |
        'strike' |
        'strong' |
        'style' |
        'sub' |
        'sup' |
        'table' |
        'tbody' |
        'td' |
        'template' |
        'textarea' |
        'tfoot' |
        'th' |
        'thead' |
        'time' |
        'title' |
        'tr' |
        'track' |
        'tt' |
        'u' |
        'ul' |
        'var' |
        'video' |
        'wbr' |
        'xmp'
    );

}
